# Generated by Django 2.2.6 on 2019-10-10 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prac', '0002_auto_20191010_2023'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
