# Generated by Django 2.2.6 on 2019-10-10 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prac', '0003_delete_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('user_id', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('guardian_phone', models.CharField(max_length=30)),
                ('aids', models.CharField(max_length=30)),
                ('push_agree', models.BooleanField()),
            ],
        ),
    ]
