# Generated by Django 2.2.6 on 2019-10-15 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=100)),
                ('location_address', models.CharField(max_length=100)),
                ('x_axis', models.FloatField()),
                ('y_axis', models.FloatField()),
                ('slope', models.IntegerField()),
                ('auto_door', models.BooleanField()),
                ('elevator', models.BooleanField()),
                ('toilet', models.BooleanField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='locationImage/')),
                ('comment', models.CharField(max_length=200)),
            ],
        ),
    ]
