# Generated by Django 2.2.6 on 2019-10-27 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0002_location_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='comment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
