# Generated by Django 2.2.6 on 2019-11-06 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0007_auto_20191107_0245'),
    ]

    operations = [
        migrations.AddField(
            model_name='fragment',
            name='road',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='information.Road'),
        ),
    ]
