# Generated by Django 2.2.6 on 2019-11-06 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0008_fragment_road'),
    ]

    operations = [
        migrations.AddField(
            model_name='fragment',
            name='slope',
            field=models.IntegerField(default=1),
        ),
    ]
