# Generated by Django 2.2.6 on 2019-11-16 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0010_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeoulElevator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.IntegerField()),
                ('station', models.CharField(max_length=300)),
                ('x_axis', models.FloatField()),
                ('y_axis', models.FloatField()),
            ],
        ),
    ]
