# Generated by Django 2.2.6 on 2019-11-29 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0012_auto_20191123_0002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('x_axis', models.FloatField()),
                ('y_axis', models.FloatField()),
                ('phone', models.CharField(max_length=100)),
                ('car', models.IntegerField()),
            ],
        ),
    ]
