# Generated by Django 2.2.6 on 2019-10-11 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20191012_0111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(default='email', max_length=10, verbose_name='유형'),
        ),
    ]
