# Generated by Django 2.2.6 on 2019-10-15 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20191012_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='guardian_phone',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='보호자 전화번호'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='전화번호'),
        ),
    ]
